root = "."
tmp_dir = "tmp"
env_files = ["example.env"]

[build]
  cmd = "mkdir -p tmp && go build -o tmp/tan-bit ."
  entrypoint = ["./tmp/tan-bit"]
  include_ext = ["go", "templ", "sql"]
  exclude_dir = ["tmp", "vendor", "db/sqlc"]
  exclude_file = ["go.sum", ".air.toml", "README.md"]
