services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file:
      - path: ./example.env
        required: true
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASSWD}
      - DB_NAME=${PG_DB_NAME}
    depends_on:
      - database
  database:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - path: ./example.env
        required: true
    environment:
      - POSTGRES_DB=${PG_DB_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWD}
