services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tan-bit-dev-app
    ports:
      - "8080:8080"
    volumes:
      # Montar todo el proyecto
      - .:/app
      # Cachea paquetes instalados
      - go-mod-cache:/go/pkg/mod
      # Cachea builds
      - go-build-cache:/root/.cache/go-build
    env_file:
      - path: ./example.env
        required: true
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASSWD}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=${DB_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
  database:
    image: postgres:15-alpine
    container_name: tan-bit-dev-pg
    env_file:
      - path: ./example.env
        required: true
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    
volumes:
  go-mod-cache:
    driver: local
  go-build-cache:
    driver: local
  pgdata:
    driver: local
