services:
  api:
    build: ./api
    container_name: tan-bit-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=3{PG_USER}
      - DB_PASSWORD=${PG_PASSWD}
      - DB_NAME=${PG_DB_NAME}
    depends_on:
      - database
    volumes:
      - ./api:/app

  database:
    image: postgres:15
    container_name: tan-bit-pg
    environment:
      - POSTGRES_DB=${PG_DB_NAME}
      - POSTGRES_USER=#{PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    
