# Etapa 1: compilar imagen
FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .
RUN CGO_ENABLED=0 go build -o /app/tan-bit

# Etapa 2: imagen final (solo el binario)
FROM alpine:3.20 AS final
RUN adduser -D -u 1000 app
USER app
COPY --from=builder /app/tan-bit /usr/local/bin/tan-bit
COPY .example.env .example.env
EXPOSE 8080
CMD ["tan-bit"]
