// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articulo.sql

package db

import (
	"context"
	"database/sql"
)

const createArticulo = `-- name: CreateArticulo :one
INSERT INTO articulo (nombre, precio, descripcion, condicion, categoria, stock, contacto)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, nombre, precio, descripcion, condicion, categoria, stock, contacto, fecha_publicacion
`

type CreateArticuloParams struct {
	Nombre      string      `json:"nombre"`
	Precio      string      `json:"precio"`
	Descripcion string      `json:"descripcion"`
	Condicion   Condicion   `json:"condicion"`
	Categoria   Categoria   `json:"categoria"`
	Stock       interface{} `json:"stock"`
	Contacto    string      `json:"contacto"`
}

type CreateArticuloRow struct {
	ID               int32        `json:"id"`
	Nombre           string       `json:"nombre"`
	Precio           string       `json:"precio"`
	Descripcion      string       `json:"descripcion"`
	Condicion        Condicion    `json:"condicion"`
	Categoria        Categoria    `json:"categoria"`
	Stock            interface{}  `json:"stock"`
	Contacto         string       `json:"contacto"`
	FechaPublicacion sql.NullTime `json:"fecha_publicacion"`
}

func (q *Queries) CreateArticulo(ctx context.Context, arg CreateArticuloParams) (CreateArticuloRow, error) {
	row := q.db.QueryRowContext(ctx, createArticulo,
		arg.Nombre,
		arg.Precio,
		arg.Descripcion,
		arg.Condicion,
		arg.Categoria,
		arg.Stock,
		arg.Contacto,
	)
	var i CreateArticuloRow
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Precio,
		&i.Descripcion,
		&i.Condicion,
		&i.Categoria,
		&i.Stock,
		&i.Contacto,
		&i.FechaPublicacion,
	)
	return i, err
}

const deleteArticulo = `-- name: DeleteArticulo :exec
DELETE FROM articulo
WHERE id = $1
`

func (q *Queries) DeleteArticulo(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteArticulo, id)
	return err
}

const getArticuloID = `-- name: GetArticuloID :one
SELECT id, nombre,precio,descripcion,condicion,categoria,stock,contacto,fecha_publicacion
FROM articulo
WHERE id = $1
`

type GetArticuloIDRow struct {
	ID               int32        `json:"id"`
	Nombre           string       `json:"nombre"`
	Precio           string       `json:"precio"`
	Descripcion      string       `json:"descripcion"`
	Condicion        Condicion    `json:"condicion"`
	Categoria        Categoria    `json:"categoria"`
	Stock            interface{}  `json:"stock"`
	Contacto         string       `json:"contacto"`
	FechaPublicacion sql.NullTime `json:"fecha_publicacion"`
}

func (q *Queries) GetArticuloID(ctx context.Context, id int32) (GetArticuloIDRow, error) {
	row := q.db.QueryRowContext(ctx, getArticuloID, id)
	var i GetArticuloIDRow
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Precio,
		&i.Descripcion,
		&i.Condicion,
		&i.Categoria,
		&i.Stock,
		&i.Contacto,
		&i.FechaPublicacion,
	)
	return i, err
}

const listArticulos = `-- name: ListArticulos :many
SELECT id, nombre, precio, descripcion, condicion, categoria, stock, contacto
FROM articulo
ORDER BY nombre
`

type ListArticulosRow struct {
	ID          int32       `json:"id"`
	Nombre      string      `json:"nombre"`
	Precio      string      `json:"precio"`
	Descripcion string      `json:"descripcion"`
	Condicion   Condicion   `json:"condicion"`
	Categoria   Categoria   `json:"categoria"`
	Stock       interface{} `json:"stock"`
	Contacto    string      `json:"contacto"`
}

func (q *Queries) ListArticulos(ctx context.Context) ([]ListArticulosRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticulos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticulosRow
	for rows.Next() {
		var i ListArticulosRow
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Precio,
			&i.Descripcion,
			&i.Condicion,
			&i.Categoria,
			&i.Stock,
			&i.Contacto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticulo = `-- name: UpdateArticulo :exec
UPDATE articulo
SET nombre = $2, precio = $3, descripcion = $4, condicion = $5, categoria = $6, stock = $7, contacto = $8
WHERE id = $1
`

type UpdateArticuloParams struct {
	ID          int32       `json:"id"`
	Nombre      string      `json:"nombre"`
	Precio      string      `json:"precio"`
	Descripcion string      `json:"descripcion"`
	Condicion   Condicion   `json:"condicion"`
	Categoria   Categoria   `json:"categoria"`
	Stock       interface{} `json:"stock"`
	Contacto    string      `json:"contacto"`
}

func (q *Queries) UpdateArticulo(ctx context.Context, arg UpdateArticuloParams) error {
	_, err := q.db.ExecContext(ctx, updateArticulo,
		arg.ID,
		arg.Nombre,
		arg.Precio,
		arg.Descripcion,
		arg.Condicion,
		arg.Categoria,
		arg.Stock,
		arg.Contacto,
	)
	return err
}
