// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type CondicionEnum string

const (
	CondicionEnumNuevo           CondicionEnum = "nuevo"
	CondicionEnumUsado           CondicionEnum = "usado"
	CondicionEnumReacondicionado CondicionEnum = "reacondicionado"
	CondicionEnumRoto            CondicionEnum = "roto"
)

func (e *CondicionEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CondicionEnum(s)
	case string:
		*e = CondicionEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for CondicionEnum: %T", src)
	}
	return nil
}

type NullCondicionEnum struct {
	CondicionEnum CondicionEnum `json:"condicion_enum"`
	Valid         bool          `json:"valid"` // Valid is true if CondicionEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCondicionEnum) Scan(value interface{}) error {
	if value == nil {
		ns.CondicionEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CondicionEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCondicionEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CondicionEnum), nil
}

type Compra struct {
	IDCompra    int32     `json:"id_compra"`
	IDComprador int32     `json:"id_comprador"`
	Fecha       time.Time `json:"fecha"`
	Total       string    `json:"total"`
}

type DetalleCompra struct {
	IDCompra                int32  `json:"id_compra"`
	IDProducto              int32  `json:"id_producto"`
	Cantidad                int32  `json:"cantidad"`
	PrecioHistoricoUnitario string `json:"precio_historico_unitario"`
}

type Producto struct {
	IDProducto  int32         `json:"id_producto"`
	Titulo      string        `json:"titulo"`
	Descripcion string        `json:"descripcion"`
	Condicion   CondicionEnum `json:"condicion"`
	Precio      string        `json:"precio"`
	Stock       int32         `json:"stock"`
	IDVendedor  int32         `json:"id_vendedor"`
}

type Usuario struct {
	IDUsuario int32  `json:"id_usuario"`
	Apellido  string `json:"apellido"`
	Nombre    string `json:"nombre"`
	Email     string `json:"email"`
}

type Vendedor struct {
	IDVendedor int32  `json:"id_vendedor"`
	Telefono   string `json:"telefono"`
}
