// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package db

import (
	"context"
	"database/sql"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO producto (
    titulo,
    descripcion,
    condicion,
    precio,
    stock,
    id_vendedor
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id_producto, titulo, descripcion, condicion, precio, stock, id_vendedor
`

type CreateProductParams struct {
	Titulo      string        `json:"titulo"`
	Descripcion string        `json:"descripcion"`
	Condicion   CondicionEnum `json:"condicion"`
	Precio      string        `json:"precio"`
	Stock       int32         `json:"stock"`
	IDVendedor  int32         `json:"id_vendedor"`
}

// Inserta un nuevo producto y devuelve el registro completo con su id generado
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Producto, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Titulo,
		arg.Descripcion,
		arg.Condicion,
		arg.Precio,
		arg.Stock,
		arg.IDVendedor,
	)
	var i Producto
	err := row.Scan(
		&i.IDProducto,
		&i.Titulo,
		&i.Descripcion,
		&i.Condicion,
		&i.Precio,
		&i.Stock,
		&i.IDVendedor,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM producto
WHERE id_producto = $1
`

// Elimina un producto por su clave primaria
func (q *Queries) DeleteProduct(ctx context.Context, idProducto int32) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, idProducto)
	return err
}

const deleteProductByIDAndSeller = `-- name: DeleteProductByIDAndSeller :execrows
DELETE FROM producto
WHERE id_producto = $1 AND id_vendedor = $2
`

type DeleteProductByIDAndSellerParams struct {
	IDProducto int32 `json:"id_producto"`
	IDVendedor int32 `json:"id_vendedor"`
}

// Elimina un producto asegurando que pertenezca al vendedor indicado
// Retorna la cantidad de filas afectadas para comprobar si se eliminó
func (q *Queries) DeleteProductByIDAndSeller(ctx context.Context, arg DeleteProductByIDAndSellerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProductByIDAndSeller, arg.IDProducto, arg.IDVendedor)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProductByID = `-- name: GetProductByID :one
SELECT id_producto, titulo, descripcion, condicion, precio, stock, id_vendedor
FROM producto
WHERE id_producto = $1
`

// Obtiene un producto por su clave primaria
func (q *Queries) GetProductByID(ctx context.Context, idProducto int32) (Producto, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, idProducto)
	var i Producto
	err := row.Scan(
		&i.IDProducto,
		&i.Titulo,
		&i.Descripcion,
		&i.Condicion,
		&i.Precio,
		&i.Stock,
		&i.IDVendedor,
	)
	return i, err
}

const getProductWithSellerDetails = `-- name: GetProductWithSellerDetails :one
SELECT
    p.id_producto,
    p.titulo,
    p.descripcion,
    p.condicion,
    p.precio,
    p.stock,
    p.id_vendedor,
    v.telefono AS vendedor_telefono,
    u.nombre AS vendedor_nombre,
    u.apellido AS vendedor_apellido,
    u.email AS vendedor_email
FROM producto p
JOIN vendedor v ON p.id_vendedor = v.id_vendedor
JOIN usuario u ON v.id_vendedor = u.id_usuario
WHERE p.id_producto = $1
`

type GetProductWithSellerDetailsRow struct {
	IDProducto       int32         `json:"id_producto"`
	Titulo           string        `json:"titulo"`
	Descripcion      string        `json:"descripcion"`
	Condicion        CondicionEnum `json:"condicion"`
	Precio           string        `json:"precio"`
	Stock            int32         `json:"stock"`
	IDVendedor       int32         `json:"id_vendedor"`
	VendedorTelefono string        `json:"vendedor_telefono"`
	VendedorNombre   string        `json:"vendedor_nombre"`
	VendedorApellido string        `json:"vendedor_apellido"`
	VendedorEmail    string        `json:"vendedor_email"`
}

// Consulta con JOIN para traer información combinada del producto y de su vendedor/usuario
func (q *Queries) GetProductWithSellerDetails(ctx context.Context, idProducto int32) (GetProductWithSellerDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getProductWithSellerDetails, idProducto)
	var i GetProductWithSellerDetailsRow
	err := row.Scan(
		&i.IDProducto,
		&i.Titulo,
		&i.Descripcion,
		&i.Condicion,
		&i.Precio,
		&i.Stock,
		&i.IDVendedor,
		&i.VendedorTelefono,
		&i.VendedorNombre,
		&i.VendedorApellido,
		&i.VendedorEmail,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id_producto, titulo, descripcion, condicion, precio, stock, id_vendedor
FROM producto
ORDER BY id_producto
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Lista productos con paginación usando LIMIT y OFFSET
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.IDProducto,
			&i.Titulo,
			&i.Descripcion,
			&i.Condicion,
			&i.Precio,
			&i.Stock,
			&i.IDVendedor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsBySeller = `-- name: ListProductsBySeller :many
SELECT id_producto, titulo, descripcion, condicion, precio, stock, id_vendedor
FROM producto
WHERE id_vendedor = $1
ORDER BY id_producto
`

// Filtra todos los productos pertenecientes a un vendedor específico
func (q *Queries) ListProductsBySeller(ctx context.Context, idVendedor int32) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, listProductsBySeller, idVendedor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.IDProducto,
			&i.Titulo,
			&i.Descripcion,
			&i.Condicion,
			&i.Precio,
			&i.Stock,
			&i.IDVendedor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProductsByTitle = `-- name: SearchProductsByTitle :many
SELECT id_producto, titulo, descripcion, condicion, precio, stock, id_vendedor
FROM producto
WHERE titulo ILIKE '%' || $1 || '%'
ORDER BY id_producto
`

// Búsqueda de productos por coincidencia parcial en el título (case-insensitive en PostgreSQL)
func (q *Queries) SearchProductsByTitle(ctx context.Context, dollar_1 sql.NullString) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, searchProductsByTitle, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.IDProducto,
			&i.Titulo,
			&i.Descripcion,
			&i.Condicion,
			&i.Precio,
			&i.Stock,
			&i.IDVendedor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
