// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seller.sql

package db

import (
	"context"
)

const createSeller = `-- name: CreateSeller :one
INSERT INTO vendedor (
    id_vendedor,
    telefono
) VALUES (
    $1, $2
)
RETURNING id_vendedor, telefono
`

type CreateSellerParams struct {
	IDVendedor int32  `json:"id_vendedor"`
	Telefono   string `json:"telefono"`
}

// Convierte a un usuario existente en vendedor registrando su teléfono
func (q *Queries) CreateSeller(ctx context.Context, arg CreateSellerParams) (Vendedor, error) {
	row := q.db.QueryRowContext(ctx, createSeller, arg.IDVendedor, arg.Telefono)
	var i Vendedor
	err := row.Scan(&i.IDVendedor, &i.Telefono)
	return i, err
}

const getSellerByID = `-- name: GetSellerByID :one
SELECT
    v.id_vendedor,
    v.telefono,
    u.nombre,
    u.apellido,
    u.email
FROM vendedor v
JOIN usuario u ON v.id_vendedor = u.id_usuario
WHERE v.id_vendedor = $1
`

type GetSellerByIDRow struct {
	IDVendedor int32  `json:"id_vendedor"`
	Telefono   string `json:"telefono"`
	Nombre     string `json:"nombre"`
	Apellido   string `json:"apellido"`
	Email      string `json:"email"`
}

// Obtiene el vendedor junto con los datos de contacto del usuario
func (q *Queries) GetSellerByID(ctx context.Context, idVendedor int32) (GetSellerByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSellerByID, idVendedor)
	var i GetSellerByIDRow
	err := row.Scan(
		&i.IDVendedor,
		&i.Telefono,
		&i.Nombre,
		&i.Apellido,
		&i.Email,
	)
	return i, err
}

const listSellers = `-- name: ListSellers :many
SELECT
    v.id_vendedor,
    v.telefono,
    u.nombre,
    u.apellido,
    u.email
FROM vendedor v
JOIN usuario u ON v.id_vendedor = u.id_usuario
ORDER BY v.id_vendedor
LIMIT $1 OFFSET $2
`

type ListSellersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSellersRow struct {
	IDVendedor int32  `json:"id_vendedor"`
	Telefono   string `json:"telefono"`
	Nombre     string `json:"nombre"`
	Apellido   string `json:"apellido"`
	Email      string `json:"email"`
}

// Lista todos los vendedores junto con su información de usuario con paginación
func (q *Queries) ListSellers(ctx context.Context, arg ListSellersParams) ([]ListSellersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSellers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSellersRow
	for rows.Next() {
		var i ListSellersRow
		if err := rows.Scan(
			&i.IDVendedor,
			&i.Telefono,
			&i.Nombre,
			&i.Apellido,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeller = `-- name: UpdateSeller :one
UPDATE vendedor
SET telefono = $2
WHERE id_vendedor = $1
RETURNING id_vendedor, telefono
`

type UpdateSellerParams struct {
	IDVendedor int32  `json:"id_vendedor"`
	Telefono   string `json:"telefono"`
}

// Actualiza el teléfono de un vendedor
func (q *Queries) UpdateSeller(ctx context.Context, arg UpdateSellerParams) (Vendedor, error) {
	row := q.db.QueryRowContext(ctx, updateSeller, arg.IDVendedor, arg.Telefono)
	var i Vendedor
	err := row.Scan(&i.IDVendedor, &i.Telefono)
	return i, err
}
