// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO usuario (
    nombre,
    apellido,
    email
) VALUES (
    $1, $2, $3
)
RETURNING id_usuario, apellido, nombre, email
`

type CreateUserParams struct {
	Nombre   sql.NullString `json:"nombre"`
	Apellido sql.NullString `json:"apellido"`
	Email    string         `json:"email"`
}

// Inserta un nuevo usuario y retorna sus datos con el ID asignado
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Nombre, arg.Apellido, arg.Email)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.Apellido,
		&i.Nombre,
		&i.Email,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id_usuario, apellido, nombre, email
FROM usuario
WHERE email = $1
`

// Obtiene un usuario a partir de su correo electrónico
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.Apellido,
		&i.Nombre,
		&i.Email,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id_usuario, apellido, nombre, email
FROM usuario
WHERE id_usuario = $1
`

// Obtiene un usuario por su clave primaria
func (q *Queries) GetUserByID(ctx context.Context, idUsuario int32) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, idUsuario)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.Apellido,
		&i.Nombre,
		&i.Email,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id_usuario, apellido, nombre, email
FROM usuario
ORDER BY id_usuario
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Lista usuarios con paginación
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.IDUsuario,
			&i.Apellido,
			&i.Nombre,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE usuario
SET
    nombre = $2,
    apellido = $3,
    email = $4
WHERE id_usuario = $1
RETURNING id_usuario, apellido, nombre, email
`

type UpdateUserParams struct {
	IDUsuario int32          `json:"id_usuario"`
	Nombre    sql.NullString `json:"nombre"`
	Apellido  sql.NullString `json:"apellido"`
	Email     string         `json:"email"`
}

// Actualiza los datos de un usuario existente
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.IDUsuario,
		arg.Nombre,
		arg.Apellido,
		arg.Email,
	)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.Apellido,
		&i.Nombre,
		&i.Email,
	)
	return i, err
}
