// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type Categoria string

const (
	CategoriaNotebook    Categoria = "notebook"
	CategoriaPantalla    Categoria = "pantalla"
	CategoriaElectronica Categoria = "electronica"
	CategoriaPeriferico  Categoria = "periferico"
	CategoriaAccesorio   Categoria = "accesorio"
	CategoriaAudio       Categoria = "audio"
	CategoriaVideo       Categoria = "video"
	CategoriaGaming      Categoria = "gaming"
)

func (e *Categoria) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Categoria(s)
	case string:
		*e = Categoria(s)
	default:
		return fmt.Errorf("unsupported scan type for Categoria: %T", src)
	}
	return nil
}

type NullCategoria struct {
	Categoria Categoria `json:"categoria"`
	Valid     bool      `json:"valid"` // Valid is true if Categoria is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCategoria) Scan(value interface{}) error {
	if value == nil {
		ns.Categoria, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Categoria.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCategoria) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Categoria), nil
}

type Condicion string

const (
	CondicionNuevo    Condicion = "nuevo"
	CondicionMuybueno Condicion = "muy bueno"
	CondicionDecente  Condicion = "decente"
	CondicionAreparar Condicion = "a reparar"
)

func (e *Condicion) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Condicion(s)
	case string:
		*e = Condicion(s)
	default:
		return fmt.Errorf("unsupported scan type for Condicion: %T", src)
	}
	return nil
}

type NullCondicion struct {
	Condicion Condicion `json:"condicion"`
	Valid     bool      `json:"valid"` // Valid is true if Condicion is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCondicion) Scan(value interface{}) error {
	if value == nil {
		ns.Condicion, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Condicion.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCondicion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Condicion), nil
}

type Articulo struct {
	ID               int32          `json:"id"`
	Nombre           string         `json:"nombre"`
	Precio           string         `json:"precio"`
	Descripcion      string         `json:"descripcion"`
	Condicion        Condicion      `json:"condicion"`
	RutaImagen       sql.NullString `json:"ruta_imagen"`
	Categoria        Categoria      `json:"categoria"`
	Stock            interface{}    `json:"stock"`
	Contacto         string         `json:"contacto"`
	FechaPublicacion sql.NullTime   `json:"fecha_publicacion"`
}
